server:
  servlet:
    context-path: /
spring:
  application:
    name: alinesno-demo-student
  datasource:
    url: jdbc:mysql://db4free.net:3306/alinesno_demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT
    username: alinesno_demo
    password: alinesno_demo
  redis:
    host: 127.0.0.1
    port: 6379   
    password: 
  devtools:
    restart:
      enabled: false 
   
dubbo:
  application:
    name: alinesno-demo-student
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  registry:
    address: zookeeper://127.0.0.1:2181
